### ISSUE TITLE
Gamma problem

### ISSUE THREAD

**Issue by divatstaff** [taysta/TaystJK#106]
Yo

I've been using Vulkan renderer for quite some time in the Tayst version and it works well, unless if i want to take screenshot (windows+shift+s, or just regular print screen) or watch back my shadowplay clips it messes up with the gamma.
Feels like it ignores my value of r_gamma 1.5 and makes the pictures, videos with default value (1) and its super dark.
I tested it, this problem only occurs while using Vulkan with other renderers its fine. 

Here's some example, both made with the same gamma yet the Vulkan one makes it really dark.
![image](https://github.com/taysta/TaystJK/assets/157291920/57601b2d-cab7-4d1b-85ba-3c1b83821bf0)
![image2](https://github.com/taysta/TaystJK/assets/157291920/fb3dcfdc-00f3-42ab-bed5-0d2ca24ff782)

**Comment by taysta** [comment]
Hey, thanks for submitting the issue. I don't personally work with the Vulkan renderer, so for this one, I'll need you to direct it towards https://github.com/JKSunny/EternalJK. That is where the Vulkan renderer is developed. When they make changes, the changes are pulled downstream into this repository also.

**Comment by divatstaff** [comment]
alright thanks for the info
