### ISSUE TITLE
Vulkan weirdness when on a map that has bsp entities and skyportals

### ISSUE THREAD

**Issue by CansecoDev** [taysta/TaystJK#107]
Can't quite put it into words, but an easy way to reproduce is to join the JoF server while it has the mp/ffa3 map loaded and walk around, here is a video showing the thing:

https://www.youtube.com/watch?v=VcX2ZBmjhJQ

**Comment by taysta** [comment]
Hey, thanks for submitting the issue. I don't personally work with the Vulkan renderer, so for this one, I'll need you to direct it towards https://github.com/JKSunny/EternalJK. That is where the Vulkan renderer is developed. When they make changes, the changes are pulled downstream into this repository also.

**Comment by taysta** [comment]
Can I just confirm that the problem doesn't happen with the vanilla renderer also? Thanks

**Comment by CansecoDev** [comment]
I doesn't happen with the Vanilla renderer, correct. Thanks for directing it to the maintainer, made the report there.

https://github.com/JKSunny/EternalJK/issues/11
