### ISSUE TITLE
/warplist and /warp names get cut off and not enough total length?

### ISSUE THREAD

**Issue by TomArrow** [taysta/TaystJK#121]
![shot2024-01-26_21-01-46](https://github.com/taysta/TaystJK/assets/6640421/ed253499-aad3-43e2-af7d-6822ff238359)

Racepack 8 from upsgaming.com. Too long mapnames break with warplist (end cut off) and some are totally missing in /warplist, probably total length of string too short.

**Comment by Alereon** [comment]
This is a jaPRO issue rather than a TaystJK issue.

1 possible solution could be sending the available warps in multiple commands instead of 1 command.

**Comment by TomArrow** [comment]
Oh sry about that. My laziness got the better of me and I just assumed it was clientside.
