### ISSUE TITLE
MSVC build fails: update_header.ps1 cannot be loaded because running scripts is disabled on this

### ISSUE THREAD

**Issue by TomArrow** [taysta/TaystJK#148]
Seems this commit broke it:
https://github.com/taysta/TaystJK/commit/c8007722a56178772ade4cde851738e15a4659c2

Is the developer expected to allow powershell scripts globally just to build TaystJK? Or am I missing something?

**Comment by TomArrow** [comment]
I suggest replacing
```
COMMAND -File "${CMAKE_SOURCE_DIR}/scripts/header/update_header.ps1" "${CMAKE_BINARY_DIR}/shared/qcommon/q_version.h")
```
with
```
COMMAND powershell -executionpolicy bypass -File "${CMAKE_SOURCE_DIR}/scripts/header/update_header.ps1" "${CMAKE_BINARY_DIR}/shared/qcommon/q_version.h")
```
(adding -executionpolicy bypass)

Works for me. 

Thanks to Daggo for the suggestion.

**Comment by taysta** [comment]
Hi Tom, 

Can you please confirm the commit in https://github.com/taysta/TaystJK/pull/149 resolves this issue.

Thanks for reporting the problem.

**Comment by taysta** [comment]
Closing the issue as the PR was merged and code changed according to your recommendation

**Comment by TomArrow** [comment]
Should work, that's the same thing I did. Thanks.
