### ISSUE TITLE
Movement: Railing collission discrepancy on base jamp server.

### ISSUE THREAD

**Issue by CansecoDev** [taysta/TaystJK#156]
**Description:**
There seems some a movement desync happening on this very specific case, kind of hard to put into words so here's the original video I made to showcase the issue: https://www.youtube.com/watch?v=A7gZQe-9mpI
The video was not taken on a purely jamp vanilla server but I later verified this on a vanilla host (steam release).

**Reproduction:**
Load a server on a vanilla jamp game and devmap t1_fatal.
Join with eternaljk, pawn and approach the railing at the beginning.
Walking angled towards the railing (forward + left or right sidestep), or doing the same + jump (again, just see he video).

**Comment by Alereon** [comment]
I am unable to reproduce this issue.

I've tried the following engines, using the vanilla game module:

jampded
OpenJKded
TaystJKded

Using client and cgame as of current master. (https://github.com/taysta/TaystJK/commit/b6f5ff52cbac9adf917e0db8078fba73a4a81207)

Can you provide us more info about which TaystJK version you're using?

**Comment by CansecoDev** [comment]
Got latest build from 2 days ago ([EternalJK: latest-b6f5ff52c - TaystJK-windows-x86_64](https://github.com/taysta/TaystJK/releases/download/latest/TaystJK-windows-x86_64.zip)) and the problem is gone, might be better to close the issue.

This issue was happening in version EternalJK: latest-dc14c44ad from 3-4 weeks ago.
