### ISSUE TITLE
Add more text colors?

### ISSUE THREAD

**Issue by Mak-Shima** [taysta/TaystJK#161]
Adding more text colors would excite a lot of people. Even if others who didnt have the client could not see them. We will have everyone using taystJK soon enough. Its already talked about on the JA streets enough.

**Comment by Alereon** [comment]
This would be possible if TaystJK was a completely standalone project.
We tend to be compatible with as many servers/clients (mods) as possible.

Adding this would be an awful experience for players who do not use TaystJK.
