### ISSUE TITLE
FIX FAST!

### ISSUE THREAD

**Issue by deprale** [taysta/TaystJK#50]
![image](https://github.com/taysta/TaystJK/assets/33827235/9894d3dc-a892-41ad-8aa0-b4cc37b06886)

the ragdoll just stood up after i suicided in console, and T-POSED!!

unplayable.

**Comment by taysta** [comment]
> ![image](https://user-images.githubusercontent.com/33827235/283678247-9894d3dc-a892-41ad-8aa0-b4cc37b06886.png)
> 
> the ragdoll just stood up after i suicided in console, and T-POSED!!
> 
> unplayable.

you are probably just missing animations for ja+ or something

**Comment by deprale** [comment]
who is ja+?

**Comment by deprale** [comment]
bump.

**Comment by deprale** [comment]
it's still happening... what the flip..

**Comment by deprale** [comment]
i tried formatting my windows and it still doesn't fix it ,what do i hae to downland?

**Comment by taysta** [comment]
> i tried formatting my windows and it still doesn't fix it ,what do i hae to downland?

what server does it happen on, i need to know exactly how to reproduce the bug to fix it. you haven't given me much information
