### ISSUE TITLE
Crashing game on Vulkan + opinion

### ISSUE THREAD

**Issue by glados1337** [taysta/TaystJK#73]
Hi,

Nice to have a frequent patches, but working stuff is more important over quantity.

I was trying Sunny EternalJK and Vulkan render working, of course there's other problem with engine, which alternate block/delays in my feelings and hit detection isn't good, maybe Vulkan is too fast render for ancient sv_fps 20. 

Also sometimes i have shuttering  even if my fps is stable 250/200 fps + can't mimize windows, depend how game starter like a weather. On EternalJK Render zero problem less fps sometimes is smoother cause of missing shuttering. On your client Vanilla render/REND2 working fine.

So i will stay on classic render. ;)
PS: RX580 4GB supporting dx12 and Vulkan

**Comment by taysta** [comment]
Hi, thanks for the feedback. I don't maintain the Vulkan renderer, any changes made on JKSunny / EternalJK are pulled downstream into this repository. If you can send me exact steps to reproduce the crash, I am happy to look into it and pass findings on to Sunny.
